// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-tYFSUt3_9r53VWboiM-q5POWY1-0IAA',
    appId: '1:630213555239:android:ca6288648c32102e5cca02',
    messagingSenderId: '630213555239',
    projectId: 'fir-95d79',
    storageBucket: 'fir-95d79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYNspqpBOjkdFzgE2cKe_fvbRFuyBmbv4',
    appId: '1:630213555239:ios:dd3ca4a251d181445cca02',
    messagingSenderId: '630213555239',
    projectId: 'fir-95d79',
    storageBucket: 'fir-95d79.appspot.com',
    androidClientId: '630213555239-0ga2vthuq8djec38f2mnunscf048sbfp.apps.googleusercontent.com',
    iosClientId: '630213555239-rp1fq395ekvq7q8hndahecm07qg7k0nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

}